name: Build AutoMirrorDisplay

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 安装 Theos（示例使用 beerpiss/theos-action）
      - name: Setup Theos
        uses: beerpiss/theos-action@v1
        with:
          theos-dir: theos

      # 编译并打包 .deb
      - name: Build Package
        run: |
          make package FINALPACKAGE=1

      # 上传 .deb 到 artifact（已升级到 v4）
      - name: Upload .deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoMirrorDisplay
          path: packages/*.deb
          if-no-files-found: error
