name: Build & Release AutoMirrorDisplay

# 提升权限以允许创建 Release
permissions:
  contents: write

on:
  push:
    # 仅当推送 tag（如 v1.2.3）时触发 release
    tags: ["v*"] # :contentReference[oaicite:0]{index=0}
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    outputs:
      deb-path: ${{ steps.rename.outputs.deb }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build deps
        run: |
          brew install dpkg ldid

      - name: Clone Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git
          mkdir -p theos/sdks
          # 可选：下载并解压 iOS 16.5 SDK 到 theos/sdks

      - name: Build .deb with dpkg-deb
        run: |
          export THEOS=${{ github.workspace }}/theos
          make package FINALPACKAGE=1 \
               THEOS_PACKAGE_SCHEME=rootless \
               INTERNAL_PACKAGE_METHOD=dpkg-deb

      - name: Rename .deb
        id: rename
        run: |
          # 直接使用 GITHUB_REF_NAME 环境变量获取 tag 名称 :contentReference[oaicite:1]{index=1}
          TAG="$GITHUB_REF_NAME"
          SRC=$(ls packages/*.deb)
          DST="AutoMirrorDisplay-${TAG}.deb"
          mv "$SRC" "packages/${DST}"
          # 将新路径输出供后续步骤使用
          echo "deb=packages/${DST}" >> $GITHUB_OUTPUT

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoMirrorDisplay-${{ github.ref_name }}.deb # :contentReference[oaicite:2]{index=2}
          path: ${{ steps.rename.outputs.deb }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') # 仅在 tag 推送时执行
    steps:
      - name: Download .deb artifact
        uses: actions/download-artifact@v4
        with:
          name: AutoMirrorDisplay-${{ github.ref_name }}.deb

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          release_name: AutoMirrorDisplay ${{ github.ref_name }}
          files: AutoMirrorDisplay-${{ github.ref_name }}.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
