name: Build & Publish AutoMirrorDisplay

on:
  push:
    branches:
    - main
  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        brew install ldid dpkg

    - name: Clone Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git
        mkdir -p theos/sdks
        # （可选）下载并解压 iOS 16.5 SDK 到 theos/sdks
        # curl -L https://github.com/theos/sdks/releases/download/.../iPhoneOS16.5.sdk.tar.xz \
        #   -o theos/sdks/iPhoneOS16.5.sdk.tar.xz
        # tar -xf theos/sdks/iPhoneOS16.5.sdk.tar.xz -C theos/sdk

    - name: Build Package with dpkg-deb
      run: |
        export THEOS=${{ github.workspace }}/theos
          # 直接调用 dpkg-deb 打包，绕过 fakeroot
        make package FINALPACKAGE=1 \
              THEOS_PACKAGE_SCHEME=rootless \
              INTERNAL_PACKAGE_METHOD=dpkg-deb

      - name: Upload .deb to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
