name: Build AutoMirrorDisplay

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. 设置 Theos 环境
      - name: Setup Theos
        uses: beerpiss/theos-action@v1
        with:
          theos-dir: theos

      # 3. 安装必要的依赖项
      - name: Install Dependencies
        run: |
          brew install ldid dpkg

      # 4. 编译并打包 .deb
      - name: Build Package
        run: |
          export THEOS=$(pwd)/theos
          make package FINALPACKAGE=1

      # 5. 上传生成的 .deb 作为构建产物
      - name: Upload .deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoMirrorDisplay
          path: packages/*.deb
          if-no-files-found: error
