name: Build & Publish AutoMirrorDisplay

on:
  push:
    tags:
      - 'v*'  # eg: v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Theos
        uses: beerpiss/theos-action@v1
        with:
          theos-dir: theos

      - name: Install Dependencies
        run: |
          brew install ldid dpkg fakeroot

      - name: Build Package
        run: |
          export THEOS=${{ github.workspace }}/theos
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload Artifact to Actions
        uses: actions/upload-artifact@v4
        with:
          name: AutoMirrorDisplay
          path: packages/*.deb
          if-no-files-found: error

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

