name: Build AutoMirrorDisplay

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 设置 Theos
        uses: beerpiss/theos-action@v1
        with:
          theos-dir: theos  # 可选，指定 Theos 的安装目录，默认为 'theos'
          theos-src: 'https://github.com/theos/theos'  # 可选，指定 Theos 的源码仓库
          theos-sdks: 'https://github.com/theos/sdks'  # 可选，指定 Theos SDKs 的仓库
          theos-sdks-ref: 'master'  # 可选，指定 SDKs 仓库的分支或标签

      # 编译并打包 .deb
      - name: Build Package
        run: |
          make package FINALPACKAGE=1

      # 上传 .deb 到 artifact（已升级到 v4）
      - name: Upload .deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoMirrorDisplay
          path: packages/*.deb
          if-no-files-found: error
