name: Build AutoMirrorDisplay

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 安装依赖项
        run: |
          sudo apt-get update
          sudo apt-get install -y git perl curl wget ldid dpkg
      - name: 克隆 Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git
          echo "THEOS=$(pwd)/theos" >> $GITHUB_ENV
      - name: 下载 SDKs
        run: |
          git clone https://github.com/theos/sdks.git
          cp -r sdks/* theos/sdks/

      # 编译并打包 .deb
      - name: Build Package
        run: |
          make package FINALPACKAGE=1

      # 上传 .deb 到 artifact（已升级到 v4）
      - name: Upload .deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoMirrorDisplay
          path: packages/*.deb
          if-no-files-found: error
